### DISCUSSION TITLE
Discussion on `sui-test-validator` docker image.

### DISCUSSION THREAD

**Discussion by vladilen11** [MystenLabs/sui#18276] [Ideas]
Last year I contributed the `sui-test-validator` dockerfile to the community(https://github.com/MystenLabs/sui/pull/14701
) and maintained a `sui-test-validator` image in my own dockerhub(https://hub.docker.com/r/vladilenaksana/sui-test-validator), where anyone can start a sui-test-validator with this docker-compose file.(this version is a bit old though)

```yaml
version: "3"

services:
  sui-test-validator-node:
    image: vladilenaksana/sui-test-validator:v0.0.3
    restart: always
    volumes:
      - ./:/app
    ports:
      - 9000:9000
      - 9123:9123
    command: ["/opt/sui/bin/sui-test-validator", "--fullnode-rpc-addr", "0.0.0.0:9000", "--faucet-addr", "0.0.0.0:9123"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://sui-test-validator-node:9123"]
      interval: 3s
      timeout: 5s
      retries: 10
```

I realize that this pr, however, isn't getting more attention, so it hasn't been merged in, but I don't have more energy to keep updating the mirrors in my dockerhub, and it would be great if the officials could merge this part of the code and maintain a sui-test-validator mirror.

Regarding `sui-test-validator`, it's a very convenient local sui move development environment for a developer to construct his own local move box and do whatever tests he wants to do in it.

If someone is asking why not just download the sui-test-validator binary instead of constructing a docker image? This is because there are a lot of people in the community who are experiencing problems with the postgres environment, and a docker image would be a good way to solve everyone's environment problems.
![image](https://github.com/MystenLabs/sui/assets/125375292/37096b4a-60f0-4272-ae28-00fc854d01bd)
