### DISCUSSION TITLE
Better theme system for the dApp Kit

### DISCUSSION THREAD

**Discussion by kkomelin** [MystenLabs/sui#18669] [General]
## Problem/Motivation

(1) Current dApp Kit theme system which is based on [Vanilla Extract](https://vanilla-extract.style/) CSS-in-JS solution is not easy to customize which prevents the Connect Button and Connect Popup from being adopted wider.

The classes which current setup of Vanilla Extract produces are scoped, for example `[data-dapp-kit].Button_buttonVariants_variant_primary__x1s81q1`, so you cannot easily override them through custom external CSS.

Many popular ecosystem projects (not by Sui Foundation) use their own custom connect buttons - we need to know why. Maybe historically because they had been built before the dApp Kit release or maybe because it's hard to integrate the connect button and popup into existing design built with Tailwind or Mui for example.

(2) Current theme system doesn't provide styles for the dark mode. An [attempt](https://github.com/MystenLabs/sui/pull/17670) to add it has been left without attention probably because of some more important priorities.

(3) Current theme system doesn't rely on Radix color scheme/variables even though the dApp Kit uses Radix under the hood. Radix has its own set of CSS variables, which the dApp Kit is not using currently.

To sum up, if one wants to integrate the ConnectButton from the dApp Kit into their project, they need to marry Radix styles, [dApp Kit styles](https://github.com/MystenLabs/sui/blob/ffd3231924e27f4099fefe380ef48b65885c0aac/sdk/dapp-kit/src/themes/lightTheme.ts) and Tailwind theme. 

## Current Workaround

Currently I use the following workaround for my Tailwind-based projects:

(1) I define a CSS variable for a common style, for example fontFamily:

```css
/* index.css */
:root {
  --sds-font-inter: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
}
```

(2) I override dApp Kit theme settings using my newly created CSS variable:

```typescript
// theme.ts
export const lightTheme: ThemeVars = {
  // ...
  typography: {
    fontFamily: 'var(--sds-font-inter)',
    // ...
  },
}
```

(3) I pass the theme to the dApp Kit wallet provider:

```tsx
// main.tsx
<WalletProvider theme={lightTheme}>
  {children}
</WalletProvider>
```

_If there is a Radix CSS variable for something like background color, we need to use it in the dApp Kit themes to better marry the different theme systems._

But this solution doesn't give me full control. For example, I still cannot change the button padding, for example, because it is not extracted to a CSS variable:

```css
[data-dapp-kit].Button_buttonVariants_size_lg__x1s81q4, [data-dapp-kit] .Button_buttonVariants_size_lg__x1s81q4 {
    border-radius: var(--dapp-kit-radii-large);
    padding: 16px 24px;
}
```

## Better Solution

I suggest us starting a discussion on how we can unify styles in the dApp Kit theme system, provide the default dark theme and make the Kit theme more customizible.
