### ISSUE TITLE
Can't publish package with rust sui-sdk

### ISSUE THREAD

**Issue by ChzenChzen** [MystenLabs/sui#10486]
Cargo.toml
```toml
[package]
name = "contracts_deployer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread"] }
# sui
sui-sdk = { git = "https://github.com/MystenLabs/sui", rev = "de632da6a" }
sui-keys = { git = "https://github.com/MystenLabs/sui", rev = "de632da6a" }
sui-framework = { git = "https://github.com/MystenLabs/sui", rev = "de632da6a" }
sui-framework-build = { git = "https://github.com/MystenLabs/sui", rev = "de632da6a" }
sui-types = { git = "https://github.com/MystenLabs/sui", rev = "de632da6a" }
shared-crypto = { git = "https://github.com/MystenLabs/sui", rev = "de632da6a" }

# logging
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-bunyan-formatter = "0.3.6"
tracing-log = "0.1.3"

eyre = "0.6.8"
dirs = "4.0.0"
reqwest = { version = "0.11.14", features = ["json"] }
serde_json = "1.0.93"
lazy-regex = "2.4.1"
once_cell = "1.17.1"
```

method which I use for publishing
```rust 
    #[instrument(name = "Publishing package", skip_all)]
    pub async fn publish_package(&self, package_path: &Path) -> Result<()> {
        let compiled_modules = build_and_compile_package(package_path)?;
        let Self { keystore, client } = self;

        let gas_object_id = self.get_gas_object_id().await?;
        let tx_data = client
            .transaction_builder()
            .publish(
                self.active_address()?,
                compiled_modules,
                Vec::new(),
                Some(gas_object_id),
                GAS_BUDGET,
            )
            .await
            .map_err(|e| eyre!(e))
            .wrap_err("Failed to build transaction for publishing package")?;

        let signature = keystore
            .sign_secure(&self.active_address()?, &tx_data, Intent::sui_transaction())
            .wrap_err("Failed to sign transaction for publishing package")?;

        let tx = Transaction::from_data(tx_data, Intent::sui_transaction(), vec![signature])
            .verify()
            .wrap_err("Failed to verify transaction for publishing package")?;

        let ret = client
            .quorum_driver()
            .execute_transaction_block(
                tx,
                SuiTransactionBlockResponseOptions::new().with_effects(),
                Some(sui_types::messages::ExecuteTransactionRequestType::WaitForLocalExecution),
            )
            .await
            .wrap_err("Failed to execute transaction for publishing package")?;
        dbg!(ret);

        Ok(())
    }
}
```

Result:
```
...

SuiTransactionBlockEffectsV1 {
                status: Failure {
                    error: "PublishUpgradeMissingDependency in command 0",
                },
                
 ...               
```
so it compiles without problem, but I get error. I tried publish very simple move package. https://github.com/battlemon-project/sui-contracts/tree/main/monolith
