### ISSUE TITLE
Sui fullnode stuck at checkpoint 0

### ISSUE THREAD

**Issue by Sotatek-SinhVu** [MystenLabs/sui#11028]
I got an issue related to sui fullnode. It is stuck at checkpoint 0. Here is the details:

- Network: testnet

- Configs:

```
# Update this value to the location you want Sui to store its database
db-path: "/home/ubuntu/.sui/db"

network-address: "/dns/localhost/tcp/8080/http"
metrics-address: "0.0.0.0:9184"
# this address is also used for web socket connections
json-rpc-address: "0.0.0.0:9000"
enable-event-processing: true

genesis:
  # Update this to the location of where the genesis file is stored
  genesis-file-location: "/home/ubuntu/.sui/genesis.blob"

authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  num-epochs-to-retain: 1
  max-checkpoints-in-batch: 200
  max-transactions-in-batch: 1000
  use-range-deletion: true
  pruning-run-delay-seconds: 60
```

- Logs:

```
sui-node[1114557]: 2023-04-18T06:47:24.371352Z  INFO sui_node: SuiNode started!
sui-node[1114557]: 2023-04-18T06:47:24.371434Z  INFO narwhal_network::connectivity: Spawning future narwhal/network/src/connectivity.rs:ConnectionMonitor
sui-node[1114557]: 2023-04-18T06:47:24.371456Z  INFO sui_node::admin: starting admin server filter=info address=127.0.0.1:1337
sui-node[1114557]: 2023-04-18T06:47:24.371985Z  INFO schedule_checkpoint{seq=0 epoch=0}: sui_core::checkpoints::checkpoint_executor: Checkpoint preparation for execution took 419.192µs
sui-node[1114557]: 2023-04-18T06:47:24.375421Z  INFO sui_core::checkpoints::checkpoint_executor: Checkpoint execution took 3.437126ms seq=0
sui-node[1114557]: 2023-04-18T06:47:24.375435Z  INFO sui_core::checkpoints::checkpoint_executor: Finished syncing and executing checkpoint 0
```

Anyone can help to check. Thanks!
