### ISSUE TITLE
[Bug] - Docker Compose to run full node fails on Config Read

### ISSUE THREAD

**Issue by KonScanner** [MystenLabs/sui#13285]
## Steps to Reproduce Issue

Following the steps here: https://github.com/MystenLabs/sui/tree/main/docker/fullnode#readme

## Expected Result

A running node.

## Actual Result

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: authority-store-pruning-config: missing field `use-range-deletion` at line 15 column 33', crates/sui-node/src/main.rs:53:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Added `RUST_BACKTRACE=1` then `RUST_BACKTRACE=full`:
```
hread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: authority-store-pruning-config: missing field `use-range-deletion` at line 15 column 33

Stack backtrace:
   0: sui_config::Config::load
   1: sui_node::main
   2: std::sys_common::backtrace::__rust_begin_short_backtrace
   3: std::rt::lang_start::{{closure}}
   4: std::rt::lang_start_internal
   5: main
   6: __libc_start_main
   7: _start', crates/sui-node/src/main.rs:53:58
stack backtrace:
   0:     0x564ecdc0e2ca - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
   1:     0x564ecdc38bde - core::fmt::write::h25eb51b9526b8e0c
   2:     0x564ecdc07585 - std::io::Write::write_fmt::ha9edec5fb1621933
   3:     0x564ecdc0e095 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
   4:     0x564ecdc0fb2f - std::panicking::default_hook::{{closure}}::h22a91871f4454152
   5:     0x564ecdc0f86b - std::panicking::default_hook::h21ddc36de0cd4ae7
   6:     0x564ecdc10239 - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
   7:     0x564ecdc0ffd9 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
   8:     0x564ecdc0e77c - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
   9:     0x564ecdc0fce2 - rust_begin_unwind
  10:     0x564ecb52ba73 - core::panicking::panic_fmt::hd1d46bcde3c61d72
  11:     0x564ecb52bf23 - core::result::unwrap_failed::h456a23f68607268c
  12:     0x564ecba5b431 - sui_node::main::he64bd19715d1fc35
  13:     0x564ecb7e4223 - std::sys_common::backtrace::__rust_begin_short_backtrace::hefafcb418b02cf66
  14:     0x564ecb923f99 - std::rt::lang_start::{{closure}}::h5421492fc1068817
  15:     0x564ecdbff5fc - std::rt::lang_start_internal::h8f7e70b1a2558118
  16:     0x564ecba5b49c - main
  17:     0x7f62fac9ed0a - __libc_start_main
  18:     0x564ecb54ee7a - _start
  19:                0x0 - <unknown>
  ```

Fails to find some sort of config call failing to load configuration.

## System Information

* OS: Ubuntu 22.04.2 LTS x86_64

**Comment by KonScanner** [comment]
Full node tutorial [here](https://docs.sui.io/build/fullnode) works, with the exception that, when I run 
```
cargo run --release --bin sui-node -- --config-path fullnode.yaml
```
And the node starts running I get:
```
2023-08-05T11:29:34.787220Z ERROR sui_network::state_sync: Failed to find an archive reader to complete the state sync request
2023-08-05T11:29:39.788055Z ERROR sui_network::state_sync: Failed to find an archive reader to complete the state sync request
2023-08-05T11:29:41.793509Z  INFO sui_network::state_sync: unable to sync contents of checkpoint 1
2023-08-05T11:29:44.789055Z ERROR sui_network::state_sync: Failed to find an archive reader to complete the state sync request
```

Maybe need to update peers on the site. Also the docker-image is still not working :(

**Comment by jiOnederfull** [comment]
Same with me.

I tried with:

1. `fullnode-template.yaml` default
```
authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  num-epochs-to-retain: 1
  max-checkpoints-in-batch: 10
  max-transactions-in-batch: 1000
  pruning-run-delay-seconds: 60
```
2. as docs says for enabling aggressive pruning:
```
authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  num-epochs-to-retain: 0
  max-checkpoints-in-batch: 10
  max-transactions-in-batch: 1000
  pruning-run-delay-seconds: 60
```
3. erase all `authority-store-pruning-config:`

But above all didn't work.
