### ISSUE TITLE
sui testnet unable to sync

### ISSUE THREAD

**Issue by wyf2317** [MystenLabs/sui#15513]
testnet  unable to sync. By metrics, the value of sui_network_peers is 0

```
curl --silent http://127.0.0.1:9184/metrics | grep sui_network_peers
# HELP sui_network_peers The number of connected peers.
# TYPE sui_network_peers gauge
sui_network_peers 0
```

p2p-config has been configured according to github information。Please tell me if there is any problem with my configuration
```
fullnode.yaml
# Update this value to the location you want Sui to store its database
db-path: "/data2/suidb"

network-address: "/dns/localhost/tcp/8080/http"
metrics-address: "0.0.0.0:9184"
# this address is also used for web socket connections
json-rpc-address: "0.0.0.0:9000"
enable-event-processing: true

genesis:
  # Update this to the location of where the genesis file is stored
  genesis-file-location: "/home/sui/sui/genesis.blob"

authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  num-epochs-to-retain: 1
  max-checkpoints-in-batch: 10
  max-transactions-in-batch: 1000
  use-range-deletion: true
  pruning-run-delay-seconds: 60

p2p-config:
  seed-peers:
    - peer-id: df8a8d128051c249e224f95fcc463f518a0ebed8986bbdcc11ed751181fecd38
      address: /dns/lax-tnt-ssfn-00.testnet.sui.io/udp/8084
    - peer-id: f9a72a0a6c17eed09c27898eab389add704777c03e135846da2428f516a0c11d
      address: /dns/lhr-tnt-ssfn-00.testnet.sui.io/udp/8084
    - peer-id: 9393d6056bb9c9d8475a3cf3525c747257f17c6a698a7062cbbd1875bc6ef71e
      address: /dns/mel-tnt-ssfn-00.testnet.sui.io/udp/8084
```

## System Information

* OS: Linux version 5.14.0-284.11.1.el9_2.x86_64
* Compiler: releases/sui-v1.15.0-release
