### ISSUE TITLE
Publish Error occurring when using sui::token

### ISSUE THREAD

**Issue by jojoo-eth** [MystenLabs/sui#16065]
Error occurring when i run:
```bash
sui client publish --gas-budget 100000000 --skip-dependency-verification

Error executing transaction: Failure {
    error: "VMVerificationOrDeserializationError in command 0",
}
```

However, when I no longer use the sui::token package, the error disappears.

Here is some infos about my envs:
```
❯ sui -V        
sui 1.17.3-ebcb58ff
```

```
[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", 
subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
```

Move Code is the example in Sui repo:
https://github.com/MystenLabs/sui/blob/mainnet/examples/move/token/sources/coffee.move

**Comment by 0xmovses** [comment]
I'm facing the same issue when I try to publish this module https://github.com/movemntdev/hyperlane-monorepo/blob/v3-sui/sui-move/isms/sources/multisig_ism.move

**Comment by tnowacki** [comment]
I see you have `--skip-dependency-verification` enabled. What happens if you remove that flag?

**Comment by tnowacki** [comment]
@jojoo-eth, it is hard to know exactly what is wrong without seeing the result without the flag. But make sure you are specifying the correct `rev` for the chain you are publishing to, e.g. `rev = "framework/testnet"` instead of `mainnet` when publishing on `testnet`

@0xmovses it looks like your local code is different from what is on chain. So you might be using some new functionality from the local checkout that is not present on-chain, which is why the package fails on publish.

**Comment by ronanyeah** [comment]
I also had this problem and it was because the package I was depending on did not have it's original deploy address in the `[addresses]` field:

- Bad ❌
```toml
[package]
name = "MyPackage"
edition = "2024.beta"
published-at = "0x00000000000000000000000000000V2"
version = "1.0.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.24.1" }

[addresses]
my_package = "0x0"
```

- Good ✅
```toml
[package]
name = "MyPackage"
edition = "2024.beta"
published-at = "0x00000000000000000000000000000V2"
version = "1.0.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.24.1" }

[addresses]
my_package = "0x00000000000000000000000000000V1"
```

---

#### Usage
```toml
[package]
name = "MyApp"
edition = "2024.beta"
published-at = "0x0000000000000000000000000000000000FOO"
version = "1.0.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.24.1" }
MyPackage = { git = "https://github.com/foo/my-package.git", rev = "master" }

[addresses]
my_app = "0x0000000000000000000000000000000000FOO"
```

The use of `0x0` for upgrading is confusing and is explained more here: https://docs.sui.io/concepts/sui-move-concepts/packages/upgrade
