### ISSUE TITLE
Sui::vdf was not found

### ISSUE THREAD

**Issue by lyanna95** [MystenLabs/sui#18251]
## Steps to Reproduce Issue
https://github.com/lyanna95/letsmove/tree/main/mover/lyanna95/code/task2/coin

```bash
sui client publish --gas-budget 100000000
```

Failed to publish the Move module(s), reason: [warning] On-chain version of dependency Sui::vdf was not found.

This may indicate that the on-chain version(s) of your package's dependencies may behave differently than the source version(s) your package was built against.

Fix this by rebuilding your packages with source versions matching on-chain versions of dependencies, or ignore this warning by re-running with the --skip-dependency-verification flag.

**Comment by stefan-mysten** [comment]
@lyanna95 thanks for this report. A couple of questions:
- What version of the Sui CLI are you using? How did you install it?
- What network are you trying to publish to?
- What is the current active network set in your CLI?

**Comment by lyanna95** [comment]
I am using 1.27.0. I create project with `sui move new coin`. I have solved this problem by modifing the dependency.
```toml
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
```
