### ISSUE TITLE
Sui full node stuck on checkpoints

### ISSUE THREAD

**Issue by cybercent** [MystenLabs/sui#18901]
## Steps to Reproduce Issue

We started running a Sui Full node back in April (version 1.23.1 - commit [Sui v1.23.1 version bump](https://github.com/MystenLabs/sui/commit/4dbcf811abde03f8b1b2bf127a0215f2f966c9c0)). 

The node is not fully-synced with the network yet, it's currently synced up to January 2024.
Recently we observed that the node is getting stuck every day for a couple of hours.

If we restart the node it gets unstuck immediately, otherwise it will unstuck itself after 2-3 hours.

We're using the fallback to the S3 bucket from Mysten.
```
fullnode/config/fullnode.yaml                                                                          

# Update this value to the location you want Sui to store its database
db-path: "/opt/sui/db"

# For ipv4, update this to "/ipv4/X.X.X.X/tcp/8080/http"
network-address: "/dns/localhost/tcp/8080/http"
metrics-address: "0.0.0.0:9184"
# this address is also used for web socket connections
json-rpc-address: "0.0.0.0:9000"
websocket-address: "0.0.0.0:9001"
enable-event-processing: true
enable-index-processing: true
enable-experimental-rest-api: true

genesis:
  # Update this to the location of where the genesis file is stored
  genesis-file-location: "/opt/sui/config/genesis.blob"

authority-store-pruning-config:
  # default values
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  max-checkpoints-in-batch: 10
  max-transactions-in-batch: 1000
  # end of default values

  # No pruning of object versions (use u64::max for num of epochs)
  num-epochs-to-retain: 18446744073709551615
  # Prune historic transactions of the past epochs
  num-epochs-to-retain-for-checkpoints: 18446744073709551615
  periodic-compaction-threshold-days: 1

p2p-config:
  seed-peers:
    - address: /dns/mel-00.mainnet.sui.io/udp/8084
      peer-id: d32b55bdf1737ec415df8c88b3bf91e194b59ee3127e3f38ea46fd88ba2e7849
    - address: /dns/ewr-00.mainnet.sui.io/udp/8084
      peer-id: c7bf6cb93ca8fdda655c47ebb85ace28e6931464564332bf63e27e90199c50ee
    - address: /dns/ewr-01.mainnet.sui.io/udp/8084
      peer-id: 3227f8a05f0faa1a197c075d31135a366a1c6f3d4872cb8af66c14dea3e0eb66
    - address: /dns/lhr-00.mainnet.sui.io/udp/8084
      peer-id: c619a5e0f8f36eac45118c1f8bda28f0f508e2839042781f1d4a9818043f732c
    - address: /dns/sui-mainnet-ssfn-1.nodeinfra.com/udp/8084
      peer-id: 0c52ca8d2b9f51be4a50eb44ace863c05aadc940a7bd15d4d3f498deb81d7fc6
    - address: /dns/sui-mainnet-ssfn-2.nodeinfra.com/udp/8084
      peer-id: 1dbc28c105aa7eb9d1d3ac07ae663ea638d91f2b99c076a52bbded296bd3ed5c
    - address: /dns/sui-mainnet-ssfn-ashburn-na.overclock.run/udp/8084
      peer-id: 5ff8461ab527a8f241767b268c7aaf24d0312c7b923913dd3c11ee67ef181e45
    - address: /dns/sui-mainnet-ssfn-dallas-na.overclock.run/udp/8084
      peer-id: e1a4f40d66f1c89559a195352ba9ff84aec28abab1d3aa1c491901a252acefa6
    - address: /dns/ssn01.mainnet.sui.rpcpool.com/udp/8084
      peer-id: fadb7ccb0b7fc99223419176e707f5122fef4ea686eb8e80d1778588bf5a0bcd
    - address: /dns/ssn02.mainnet.sui.rpcpool.com/udp/8084
      peer-id: 13783584a90025b87d4604f1991252221e5fd88cab40001642f4b00111ae9b7e

state-archive-read-config:
  - object-store-config:
      object-store: "S3"
      bucket: "mysten-mainnet-archives"
      aws-access-key-id: "access_key_id"
      aws-secret-access-key: "access_key_secret"
      aws-region: "us-west-2"
      object-store-connection-limit: 20
    concurrency: 5
    use-for-pruning-watermark: false
```

We are also running the indexer service on the same code version from April.

It appears (https://github.com/MystenLabs/sui/issues/18773#issuecomment-2245798942) that we could solve the issue by updating the node and the indexer. 

The problem with that is that the indexer has breaking changes and we would need to reindex from zero and lose all the data.
https://github.com/MystenLabs/sui/pull/18495#issuecomment-2260880154

## Expected Result

Expecting the node to sync.

## Actual Result

Node gets stuck for multiple hours.
![image (5)](https://github.com/user-attachments/assets/3130a143-b3ac-4cdc-b5fc-ca10c448217d)

## System Information

Running the node on the recommended machine type on GCP.
