### ISSUE TITLE
Unable To Recover Sui Nodes After Power Loss - Mainnet v1.30.1

### ISSUE THREAD

**Issue by ymonye** [MystenLabs/sui#18972]
Hi team,

My RPC node service LedgerQL has experienced two unplanned power losses this past year on servers running Sui (archive / non-prunned) mainnet nodes, and upon server reboot these Sui nodes have been unable to re-sync. I'm opening up this issue not only for a resolution to recover both of our nodes, but to also address concerns with how Sui handles any unplanned service interruptions, as we've not faced this with any of our EVM, Cosmos SDK, Solana, and alternative MoveVM (Aptos) nodes. Also these Sui mainnet nodes are roughly 7TB in size, so a full snapshot recovery is incredibly taxing from a resource standpoint.

The 1st occurrence was February 29th 2024, from the below Discord link:
https://discord.com/channels/916379725201563759/968392942517649438/1212535832045551736

After a server boot, one of our Sui mainnet nodes produced the below logs, failing to sync, while the other node synced without issue. We were unable to come to a resolution within the Discord conversation, so that particular Sui node was scrubbed and replaced with the secondary node that was syncing without issue.

```
fullnode-01-fullnode-1  | 2024-02-28T23:02:15.108377Z  INFO sui_core::authority::authority_store_pruner: Manual compaction of sst file "/2330345.sst". Size: 134411439, level: 4
fullnode-01-fullnode-1  | 2024-02-28T23:02:19.276637Z  WARN sui_core::checkpoints::checkpoint_executor: Received no new synced checkpoints for 2s. Next checkpoint to be scheduled: 27396607
fullnode-01-fullnode-1  | 2024-02-28T23:02:19.347475Z  INFO sui_core::authority::authority_store_pruner: Manual compaction of sst file "/693257.sst". Size: 134409054, level: 4
fullnode-01-fullnode-1  | 2024-02-28T23:02:20.427060Z  INFO sui_core::authority::authority_store_pruner: Manual compaction of sst file "/617889.sst". Size: 134408725, level: 4
```

Yesterday after a power loss & recovery, both of our nodes are unable to recover. The primary node returns the below, erroring & exiting the application after a few seconds:

```
2024-08-13T00:38:10.730029Z  INFO sui_node: Sui JSON-RPC server listening on 0.0.0.0:9000 local_addr=0.0.0.0:9000
2024-08-13T00:38:10.730139Z  INFO sui_node: SuiNode started!
2024-08-13T00:38:10.730220Z  INFO narwhal_network::connectivity: Spawning future narwhal/network/src/connectivity.rs:ConnectionMonitor
2024-08-13T00:38:10.730320Z  INFO sui_node: Sui chain identifier: 35834a8a
2024-08-13T00:38:10.730467Z  INFO sui_node::admin: starting admin server filter=info address=127.0.0.1:1337
thread '2024-08-13T00:38:10.774653Z ERROR telemetry_subscribers: panicked at crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs:1223:21:
Transaction effects for effects digest TransactionEffectsDigest(F7oPMEsvEiMbVi97HAwz6LsQHnHhSFYrYkNHceQ6emCC) do not exist in effects table panic.file="crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs" panic.line=1223 panic.column=21
sui-node-runtime' panicked at crates/sui-core/src/checkpoints/checkpoint_executor/mod.rs:1223:21:
Transaction effects for effects digest TransactionEffectsDigest(F7oPMEsvEiMbVi97HAwz6LsQHnHhSFYrYkNHceQ6emCC) do not exist in effects table
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The second Sui node returns the below, without syncing any new checkpoints after running for several hours:

```
fullnode-02-fullnode-1  | 2024-08-13T14:02:56.432253Z  INFO sui_network::state_sync: unable to sync contents of checkpoint through state sync 46864354 with lowest peer checkpoint: 1
fullnode-02-fullnode-1  | 2024-08-13T14:02:56.432383Z  INFO sui_core::checkpoints::checkpoint_executor: Received checkpoint summary from state sync sequence_number=46864352
fullnode-02-fullnode-1  | 2024-08-13T14:02:56.432428Z  INFO sui_core::checkpoints::checkpoint_executor: Received checkpoint summary from state sync sequence_number=46864353
fullnode-02-fullnode-1  | 2024-08-13T14:02:56.487469Z  INFO sui_network::state_sync: unable to sync contents of checkpoint through state sync 46864356 with lowest peer checkpoint: 1
fullnode-02-fullnode-1  | 2024-08-13T14:02:56.487634Z  INFO sui_core::checkpoints::checkpoint_executor: Received checkpoint summary from state sync sequence_number=46864354
fullnode-02-fullnode-1  | 2024-08-13T14:02:56.487682Z  INFO sui_core::checkpoints::checkpoint_executor: Received checkpoint summary from state sync sequence_number=46864355
fullnode-02-fullnode-1  | 2024-08-13T14:02:56.515740Z  INFO sui_network::state_sync: unable to sync contents of checkpoint through state sync 46864357 with lowest peer checkpoint: 1
```

Both nodes are running on v1.30.1, mysten/sui-node:a4185da5659d8d299d34e1bb2515ff1f7e32a20a, using the Docker compose from https://github.com/MystenLabs/sui/tree/main/docker/fullnode.

Below are the contents of fullnode-template.yml:

```
# Update this value to the location you want Sui to store its database
db-path: "suidb"

network-address: "/dns/localhost/tcp/8080/http"
metrics-address: "0.0.0.0:9184"
# this address is also used for web socket connections
json-rpc-address: "0.0.0.0:9000"
enable-event-processing: true

genesis:
  # Update this to the location of where the genesis file is stored
  genesis-file-location: "genesis.blob"

authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 500000
  epoch-db-pruning-period-secs: 3600
  num-epochs-to-retain: 500000
  max-checkpoints-in-batch: 10
  max-transactions-in-batch: 1000
  num-epochs-to-retain-for-checkpoints: 500000
  periodic-compaction-threshold-days: 1

p2p-config:
  seed-peers:
    - address: /dns/icn-00.mainnet.sui.io/udp/8084
      peer-id: 303f1f35afc9a6f82f8d21724f44e1245f4d8eca0806713a07c525dadda95a66
    - address: /dns/icn-01.mainnet.sui.io/udp/8084
      peer-id: cb7ce193cf7a41e9cc2f99e65dd1487b6314a57c74be42cc8c9225b203301812
    - address: /dns/mel-00.mainnet.sui.io/udp/8084
      peer-id: d32b55bdf1737ec415df8c88b3bf91e194b59ee3127e3f38ea46fd88ba2e7849
    - address: /dns/mel-01.mainnet.sui.io/udp/8084
      peer-id: bbf3be337fc16614a1953da83db729abfdc40596e197f36fe408574f7c9b780e
    - address: /dns/ewr-00.mainnet.sui.io/udp/8084
      peer-id: c7bf6cb93ca8fdda655c47ebb85ace28e6931464564332bf63e27e90199c50ee
    - address: /dns/ewr-01.mainnet.sui.io/udp/8084
      peer-id: 3227f8a05f0faa1a197c075d31135a366a1c6f3d4872cb8af66c14dea3e0eb66
    - address: /dns/sjc-00.mainnet.sui.io/udp/8084
      peer-id: 6f0b25087cd6b2fd2e4329bcf308ac95a37c49277dd7286b72470c124809db5b
    - address: /dns/sjc-01.mainnet.sui.io/udp/8084
      peer-id: af1d5d8468b3612ac2b6ff3ca91e99a71390dbe5b83dea9f6ae2da708d689227
    - address: /dns/lhr-00.mainnet.sui.io/udp/8084
      peer-id: c619a5e0f8f36eac45118c1f8bda28f0f508e2839042781f1d4a9818043f732c
    - address: /dns/lhr-01.mainnet.sui.io/udp/8084
      peer-id: 53dcedf250f73b1ec83250614498947db00d17c0181020fcdb7b6db12afbc175
```
