### ISSUE TITLE
Namespace collision between packages' dependencies

### ISSUE THREAD

**Issue by Oni-giri** [MystenLabs/sui#20112]
## Steps to Reproduce Issue

Consider an empty project with the following `Move.toml`:
```toml
[package]
name = "test"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
Sui = { override = true, git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
ScallopProtocol = { git = "https://github.com/scallop-io/sui-lending-protocol.git", subdir = "contracts/protocol", rev = "mainnet" }
lending_core = { git = "https://github.com/naviprotocol/protocol-interface.git", subdir = "lending_core", rev = "main" }
```

## Expected Result

Everything compiles

## Actual Result

Calling `sui move build` will return the following error:

```
Failed to build Move modules: Processing dependency 'lending_core' of 'test'

Caused by:
    Conflicting assignments for address 'math': '0x0' and '0x66aa3335901ce7e04b85ed6597ee42d4b479f7110bf98e8ebd474fa32a0027e1'..
```

## Remarks

Note that removing `ScallopProtocol` or `lending_core` (Navi Finance) will compile fine.

The issue here is likely that both protocols use their own `math` dependency :
- Scallop : https://github.com/scallop-io/sui-lending-protocol/blob/2c7228c091de62e496c6313d5bd1fdddfd14f6eb/contracts/protocol/Move.toml#L12
- Navi : https://github.com/naviprotocol/protocol-interface/blob/ebde5d2efacbc3faf98af1147c5fba082221ddee/lending_core/Move.toml#L12

Given that both libraries are not overlapping, we can't try to override it.

## System Information

* OS: Ubuntu 20.04
* Compiler: sui 1.36.1-homebrew

**Comment by tzakian** [comment]
Hi there!

This is a problem due to Scallop and Navi exposing two different named addresses with the same name. This should be able to be resolved using the `addr_susbst` form in the `Move.toml` which can be used to rename the `math` named address on either or both of the packages that bring the `math` address into scope. Give this a shot and it should work:

```toml
[package]
name = "test"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
Sui = { override = true, git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
ScallopProtocol = { git = "https://github.com/scallop-io/sui-lending-protocol.git", subdir = "contracts/protocol", rev = "mainnet", addr_subst = {"scallop_math" = "math" } }
lending_core = { git = "https://github.com/naviprotocol/protocol-interface.git", subdir = "lending_core", rev = "main", addr_susbst = {"lending_math" = "math" } }

```

**Comment by Oni-giri** [comment]
Thanks a lot ! It works!

**Comment by Oni-giri** [comment]
Hi @tzakian thanks again for the fix ! I added Suilend to the mix, and now it's broken again. I have tried all combinations available, and I can't get it to compile, so I'm calling for your wisdom (again!).

Here is the TOML:

```toml
[package]
name = "my_project"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
Sui = { override = true, git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
MoveStdlib = { override = true, git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/mainnet" }
suilend = { git = "https://github.com/solendprotocol/suilend.git", subdir = "contracts/suilend/", rev = "mainnet"  }
ScallopProtocol = { git = "https://github.com/scallop-io/sui-lending-protocol.git", subdir = "contracts/protocol", rev = "mainnet", addr_subst = {"scallop_math" = "math" } }
lending_core = { git = "https://github.com/naviprotocol/protocol-interface.git", subdir = "lending_core", rev = "main", addr_susbst = {"lending_math" = "math"} }
````

Which leads to :

```bash
Failed to build Move modules: When resolving dependencies for package aftermath_grow, conflicting versions of package Pyth found:
At lending_core -> oracle -> Pyth
        Pyth = { git = "https://github.com/naviprotocol/pyth-crosschain.git", rev = "navi-forked", subdir = "target_chains/sui/contracts" }
At suilend -> Pyth
        Pyth = { git = "https://github.com/solendprotocol/pyth-crosschain.git", rev = "98e218c64bb75cf1350eb7b021e1ffcc3aedfd62", subdir = "target_chains/sui/contracts" }.
```

Trying to add  `addr_subst = {"suilend_pyth" = "pyth" }` and ``addr_susbst = {"lending_math" = "math", "navi_pyth"= "pyth" }` doesn't work either.
