### ISSUE TITLE
TS-SDK does not support automatic address management (deploy/upgrade)

### ISSUE THREAD

**Issue by web3olalala** [MystenLabs/sui#20466]
Currently Sui binary supports automatic address management, but TS-SDK doesn't support it .

**Comment by stefan-mysten** [comment]
Thanks @web3olalala for this request. Passed it on to the right folks!

**Comment by web3olalala** [comment]
@stefan-mysten @hayes-mysten Is there a timeline for adding this part of the functionality, as we are developing a tool that will need to use this functionality🙏

**Comment by hayes-mysten** [comment]
This isn't something on our roadmap.  Can you elaborate on what you are hoping for with this change?  The SDK runs in a lot of different environments, and there isn't a consistent way to securely store keys across those environments

**Comment by web3olalala** [comment]
@hayes-mysten https://docs.sui.io/concepts/sui-move-concepts/packages/automated-address-management
The relevant content is here.

Example:
I have deployed PackageA.
Now I need to deploy PackageB, which is dependent on PackageA.
PackageB's Toml:
```toml
[package]
name = "packageB"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.36.2" }
PackageA = { local = "/Volumes/project/packageA" }

[addresses]
sui = "0x2"
packageB = "0x0"
```
Sui binary is able to deploy PackageB successfully because it will do address management automatically, but it is not able to deploy successfully with TS-SDK.
