### ISSUE TITLE
Websocket endpoint not working for testnet v1.41.0 version returning Disconnected (code: 1006, reason: "")

### ISSUE THREAD

**Issue by jay-ginco** [MystenLabs/sui#20959]
## Steps to Reproduce Issue

I am running testnet full node with version 1.41.0, with below fullnode template, after I recovered the node from db snapshot, it starts syncing, and the json-rpc endpoint is working as expected, but the websocket requests are failing. I also run a mainnet node, and there both the requests are working as expected

```
# Update this value to the location you want Sui to store its database
db-path: "/opt/sui/db"

# For ipv4, update this to "/ipv4/X.X.X.X/tcp/8080/http", for dns "/dns/localhost/tcp/8080/http"
network-address: "/dns/localhost/tcp/8080/http"
metrics-address: "0.0.0.0:9184"
# this address is also used for web socket connections
json-rpc-address: "0.0.0.0:9000"
jsonrpc-server-type: "both"
enable-event-processing: true

genesis:
  # Update this to the location of where the genesis file is stored
  genesis-file-location: "/opt/sui/config/genesis.blob"


authority-store-pruning-config:
  # default values
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  max-checkpoints-in-batch: 10
  max-transactions-in-batch: 1000
  # end of default values

  # No pruning of object versions (use u64::max for num of epochs)
  num-epochs-to-retain: 18446744073709551615
  # Prune historic transactions of the past epochs
  num-epochs-to-retain-for-checkpoints: 2
  periodic-compaction-threshold-days: 1
  # Smooth pruning traffic throughout an epoch
  smooth: true

state-archive-read-config:
  - object-store-config:
      object-store: "S3"
      # Use mysten-testnet-archives for testnet 
      # Use mysten-mainnet-archives for mainnet
      bucket: "mysten-testnet-archives"
      # you can either provide your own aws credentials via "aws-secret-access-key" and
      # "aws-access-key-id" or set no-sign-request: true
      no-sign-request: true
      aws-region: "us-west-2"
      object-store-connection-limit: 20
    # How many objects to read ahead when catching up  
    concurrency: 5
    # Whether to prune local state based on latest checkpoint in archive.
    # This should stay false for most use cases
    use-for-pruning-watermark: false

p2p-config:
  seed-peers:
   - address: "/dns/sui-rpc-pt.testnet-pride.com/udp/8084"
     peer-id: 0b10182585ae4a305721b1823ea5a9c3ce7d6ac4b4a8ce35fe96d9914c8fcb73
   - address: "/dns/sui-rpc-pt2.testnet-pride.com/udp/8084"
     peer-id: bf45f2bd2bbc4c2d53d10c05c96085d4ef18688af04649d6e65e1ebad1716804
   - address: "/ip4/38.242.197.20/udp/8080"
   - address: "/ip4/178.18.250.62/udp/8080"
   - address: "/ip4/162.55.84.47/udp/8084"
   - address: "/dns/wave-3.testnet.n1stake.com/udp/8084"
   - peer-id: df8a8d128051c249e224f95fcc463f518a0ebed8986bbdcc11ed751181fecd38
     address: /dns/lax-tnt-ssfn-00.testnet.sui.io/udp/8084
   - peer-id: f9a72a0a6c17eed09c27898eab389add704777c03e135846da2428f516a0c11d
     address: /dns/lhr-tnt-ssfn-00.testnet.sui.io/udp/8084
   - address: /dns/mel-tnt-ssfn-00.testnet.sui.io/udp/8084
   
```

## Expected Result
The websocket request should be connected

## Actual Result

Returns below error
```
Connected (press CTRL+C to quit)
Disconnected (code: 1006, reason: "")
```

## System Information

* OS: Ubuntu 22.04
Testnet version 1.41.0
