### ISSUE TITLE
sui_tryMultiGetPastObjects always returns 'version not found'

### ISSUE THREAD

**Issue by tmeinlschmidt** [MystenLabs/sui#22355]
We're running mutliple sui nodes and this query always returns VersionNotFound response. Is there any configuration hint, how to have nodes configured properly to keep this info (as archive node)?

query:
````
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "sui_tryMultiGetPastObjects",
    "params": [
        [
            {
                "objectId": "0x1de5cc16141c21923bfca33db9bb6c604de5760e4498e75ecdfcf80d62fb5818",
                "version": "476134977"
            }
        ],
        {
            "showType": true,
            "showOwner": true,
            "showPreviousTransaction": true,
            "showDisplay": true,
            "showContent": true,
            "showBcs": true,
            "showStorageRebate": true
        }
    ]
}
````

response:
````
{"jsonrpc":"2.0","id":1,"result":[{"status":"VersionNotFound","details":["0x1de5cc16141c21923bfca33db9bb6c604de5760e4498e75ecdfcf80d62fb5818",476134977]}]}
````

latest sui version 1.49.2

config:
````
authority-store-pruning-config:
  num-latest-epoch-dbs-to-retain: 3
  epoch-db-pruning-period-secs: 3600
  num-epochs-to-retain: 18446744073709551615
  num-epochs-to-retain-for-checkpoints: 2
  max-checkpoints-in-batch: 10
  max-transactions-in-batch: 1000
  pruning-run-delay-seconds: 60
....
state-archive-read-config:
  - ingestion-url: "https://checkpoints.mainnet.sui.io"
    # How many objects to read ahead when catching up
    concurrency: 5
````

we also store checkpoints to our s3 and it's listed in `state-archive-read-config` with `use-for-pruning-watermark: true`. Tried various configurations and had no luck.
