### ISSUE TITLE
ListOwnedObjects method on LiveDataService gRPC returns an error

### ISSUE THREAD

**Issue by briankariuki** [MystenLabs/sui#22558]
## Steps to Reproduce Issue

Calling the gRPC ListOwnedObjects returns an error

```
grpcurl -d '{"owner": "0xc75ff8f7215e3dc9671ae2ef85c519414b886bff4e0f6edb5ff7b8d3d9e648fa"}' fullnode.testnet.sui.io:443 sui.rpc.v2alpha.LiveDataService/ListOwnedObjects
```
Returns
```
ERROR:
  Code: NotFound
  Message: 
```

**Comment by bmwill** [comment]
Some of these new endpoints (including this one) require a new set of indexes that aren't initialized on all public fullnodes yet. This will change within the next few weeks though.

**Comment by briankariuki** [comment]
> Some of these new endpoints (including this one) require a new set of indexes that aren't initialized on all public fullnodes yet. This will change within the next few weeks though.

Thanks. Can I use these apis with a local sui node? I'm building a library to interact with sui from elixir.

**Comment by bmwill** [comment]
> Thanks. Can I use these apis with a local sui node? I'm building a library to interact with sui from elixir.

Yes you can! you'll just need to enable the `rpc.enable-indexing: true` in the node's yaml config before startup.

Also note that these apis are pre-stable but will become stabilized over the next few months. See https://docs.sui.io/guides/developer/getting-started/data-serving#grpc-api for more details on the timeline

**Comment by briankariuki** [comment]
Not sure how to enable `rpc.enable-indexing: true`. I'm using sui cli

**Comment by stefan-mysten** [comment]
You'll need to create your own genesis and edit the config for the fullnode. Look into `sui genesis` and use the `--write-config` flag there. Once you have your genesis, then you can start a local network from that config with `sui start --network.config [path]`. Hope this helps.

**Comment by briankariuki** [comment]
Thanks.

**Comment by briankariuki** [comment]
@stefan-mysten Thanks for your help. I was able to generate the network.yml file. My current problem is that I don't know which port the gRPC endpoint is listening at, I tried 9000 and it did not work. Another issue is that I couldn't get the faucet to work either using `-- with-faucet` argument or running the `sui-faucet` independently. It always fails with the error `Wallet Error: `No address found with sufficient coins`

**Comment by stefan-mysten** [comment]
@briankariuki here's what I would suggest then. First, backup your `sui.keystore` from `~/.sui/sui_config`. Very important to make a copy in a different folder!!! 

Then I would simply delete the `~/.sui` folder, and do instead a `sui start --with-faucet`. This will generate a new genesis and store all the configuration files in `~/.sui/sui_config`. In there, you will have a `fullnode.yaml` file with a bunch of stuff. This way you can always stop and start the network without losing the data.

The one that was generated on my local machine as above looks like below. Note that there is a `rpc: enable-indexing: true`. That's the config @bmwill was mentioning above. Try that and tell me how things go!
```
---
protocol-key-pair:
  value: FLqEwJjVU7EknXixLloQLDJ8M4WYJO65oPzpyfGEd0M=
worker-key-pair:
  value: AG7AMCbaulAw2myy/fREeWjt+A6Pi9yrIvfLUcJ/8vET
account-key-pair:
  value: ADmcWV3sPSvtC84rXIBq+YbpDiUGpEXaVgU0tOe5pclx
network-key-pair:
  value: AMm4EQvyNIJmullzxv7EBIsXoOlKYunzyZF4C9b5D0P+
db-path: full_node_db/full_node_db/b5e45b6ce56a
network-address: /ip4/127.0.0.1/tcp/55959/http
json-rpc-address: "0.0.0.0:9000"
rpc:
  enable-indexing: true
metrics-address: "127.0.0.1:55973"
admin-interface-port: 55975
enable-index-processing: true
jsonrpc-server-type: ~
grpc-load-shed: ~
grpc-concurrency-limit: ~
p2p-config:
  listen-address: "127.0.0.1:55961"
  external-address: /ip4/127.0.0.1/udp/55961
  seed-peers:
    - peer-id: a33db1559ad85fd4c0f19b3de405b81a2877a707ec6748496e4dd7d063bbbf50
      address: /ip4/127.0.0.1/udp/55943
  state-sync:
    checkpoint-content-timeout-ms: 10000
genesis:

```
