### ISSUE TITLE
Fullnode starts calculate transactions from 0 after restarting container

### ISSUE THREAD

**Issue by zavodnyuk** [MystenLabs/sui#5903]
## Steps to Reproduce Issue

1. `docker-compose up -d`
2. Let it run some time
3. `docker-compose restart`

## Expected Result
Transaction data should persist in DB  and after restarted should lcontinue from the same transaction it was before restarting

## Actual Result

Either Prometheus metrics `total_transaction_certificates`
and
json rpc 
```
curl --location --request POST http://127.0.0.1:9000/ \
  --header 'Content-Type: application/json' \
  --data-raw '{ "jsonrpc":"2.0", "method":"sui_getTotalTransactionNumber","id":1}' 
```
returns 0.

## System Information

* OS: Ubuntu 20
* Compiler: Docker image d70c0ec6922a

My docker-compose.yaml

```
version: "3.3"
services:
  fullnode:
    image: mysten/sui-node:stable
    ports:
    - "9000:9000"
    - "9184:9184"
    expose:
    - "9000"
    - "9184"
    volumes:
    - /var/sui/fullnode.yaml:/sui/fullnode.yaml:ro
    - /var/sui/genesis.blob:/var/sui/genesis.blob:ro
    - /var/sui/db:/var/sui/suidb:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
    restart: always
    deploy:
      resources:
        limits:
          memory: 6168M

volumes:
  suidb:
```
I track it on grafana dashboard, so after just restarting container transaction sync drops to 0

![image](https://user-images.githubusercontent.com/12985359/200251881-f7a08988-a289-45da-b966-6dc5574e1836.png)

Also DB isn't erased after restart,as free memory metrics hasn't changed, so it just somehow ignore history and maybe get results from RAM. Please investigate
