### ISSUE TITLE
Node sync issue

### ISSUE THREAD

**Issue by Romainua** [MystenLabs/sui#8036]
Ran node via docker compose. Used `f23377f17f48455c85ea8128f60b9ceaf7b3d4a4`. 
It is syncing to 10m txs and then it panicked and exict. My configuration and output is below.

**Hardware**
12 Core
128Gb RAM
2TB SSD

fullnode-template.yaml
```
# Update this value to the location you want Sui to store its database
db-path: "suidb"

network-address: "/dns/localhost/tcp/8080/http"
metrics-address: "0.0.0.0:9185"
json-rpc-address: "0.0.0.0:9002"
websocket-address: "0.0.0.0:9003"
enable-event-processing: true

genesis:
  # Update this to the location of where the genesis file is stored
  genesis-file-location: "genesis.blob"
p2p-config:
  seed-peers:
    - address: /dns/ams-suifn-ss1.testnet.sui.io/udp/8084
    - address: /dns/sgp-suifn-ss2.testnet.sui.io/udp/8084
    - address: /dns/icn-suifn-ss3.testnet.sui.io/udp/8084
    - address: /dns/ord-suifn-ss4.testnet.sui.io/udp/8084
  listen-address: 0.0.0.0:8084
  external-address: "/dns/fn.n1.gransl.com/udp/8084"
  anemo-config:
    max-concurrent-connections: 100 
```
docker-compose.toml
```
---
version: "3.9"
services:
  fullnode:
    image: mysten/sui-node:f23377f17f48455c85ea8128f60b9ceaf7b3d4a4
    ports:
    - "9002:9002"
    - "9185:9185"
    - "8084:8084"
    expose:
    - "9002"
    - "9185"
    - "8084"
    volumes:
    - ./fullnode-template.yaml:/sui/fullnode.yaml:ro
    - ./genesis.blob:/sui/genesis.blob:ro
    - suidb:/sui/suidb:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
volumes:
  suidb:
```

![sync_issue](https://user-images.githubusercontent.com/44613085/216457963-aae9c900-c44b-4f50-952f-3f11224fab30.png)
