### ISSUE TITLE
sui_publish API failing on 0.24.0

### ISSUE THREAD

**Issue by FrankC01** [MystenLabs/sui#8135]
I get this error using `sui_publish`:
```json
    "effects": {
      "transactionEffectsDigest": "EgPyF25MrL6ve/TXvK1ktpr88eHCuiwhRTmvj5nhSI4=",
      "effects": {
        "status": {
          "status": "failure",
          "error": "VMVerificationOrDeserializationError",
          "succeeded": false
        },
```
I know that the flag `--skip-dependency-verification` but that (and other CLI options) are not available via RPC API

**I have 1 parent and 1 child project:**

### Child Move.toml
```toml
[package]
name = "SuiChild"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }

[addresses]
suichild = "0x0"
sui =  "0000000000000000000000000000000000000002"
```
### Child source
```rust
module suichild::child {

    use sui::object:: UID;
    use sui::tx_context::TxContext;
    /// Child struct
    struct Child has key {
        id: UID,
        admin: address,
        epoch_id: u64,
    }

    fun init(_: &mut TxContext) {}

    /// Fetch child epoch sequence
    public fun child_epoch(self: &Child): u64 {
        self.epoch_id
    }
}
```

### Parent Move.toml
```toml
[package]
name = "SuiParent"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
SuiChild = { local = "../child"}

[addresses]
sui =  "0000000000000000000000000000000000000002"
suiparent =  "0x0"
```

### Parent source
```rust
module suiparent::base {

    use sui::object::UID;
    use sui::tx_context::TxContext;
    use suichild::child::{Child, child_epoch};

    struct Parent has key {
        id: UID,
        admin: address,
        epoch: u64,
    }

    fun init(_: &mut TxContext) {}

    public entry fun get_child_epoch(child: &Child, _: &mut TxContext) {
        let ce = child_epoch(child);
        assert!(ce == 0, 5)
    }
}
```
